services:
  - type: web
    name: my-academy-quest
    env: ruby
    buildCommand: >
      bundle install &&
      yarn install --check-files &&
      bundle exec rake assets:precompile &&
      bundle exec rake assets:clean
    startCommand: bundle exec puma -C config/puma.rb
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
    releaseCommand: bundle exec rails db:migrate
